name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # FIX: The original 'Build with Gradle' step has been replaced by two new steps
      # to give us direct control over the caching feature that is causing the build to fail.

      - name: Set up Gradle and Disable Cache
        uses: gradle/actions/setup-gradle@v3
        with:
          # This is the most important line. It tells the workflow to skip trying
          # to connect to the broken cache service, which will fix your error.
          cache-disabled: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
