name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # FIX: Reverting to a single, more robust Gradle action.
      # This action handles the setup and build process internally, which avoids
      # the 'gradlew: No such file or directory' error.

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          # This argument disables the cache, which was the original problem.
          cache-disabled: true 
          # This argument tells the action what to build.
          arguments: app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
