name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          # --- THIS IS THE FINAL FIX ---
          # The Android Gradle Plugin 7.4.2 requires Gradle version 7.5 or higher.
          gradle-version: '7.5'

          # This is to prevent a potential cache error.
          cache-disabled: true

          # This is the command to build your app.
          arguments: app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk